In [2]:
import os
from pathlib import Path
import sys
import argparse
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv(r"E:\Computer Graphics\SorghumData\524042_33.08_-111.97_2021.csv", skiprows=2)

In [8]:
df.head()

,Year,Month,Day,Hour,Minute,DHI,DNI,GHI,Clearsky DHI,Clearsky DNI,...,Dew Point,Solar Zenith Angle,Fill Flag,Surface Albedo,Wind Speed,Precipitable Water,Wind Direction,Relative Humidity,Temperature,Pressure
0,2021,1,1,0,0,0,0,0,0,0,...,-10.1,167.75,0,0.24,1.1,0.9,28,26.81,7.9,968
1,2021,1,1,0,5,0,0,0,0,0,...,-10.1,168.34,0,0.24,1.0,0.9,28,26.81,7.9,968
2,2021,1,1,0,10,0,0,0,0,0,...,-10.1,168.85,0,0.24,1.0,0.9,29,26.99,7.8,968
3,2021,1,1,0,15,0,0,0,0,0,...,-10.1,169.26,0,0.24,1.0,0.9,29,26.99,7.8,968
4,2021,1,1,0,20,0,0,0,0,0,...,-10.1,169.58,0,0.24,1.0,0.9,30,26.99,7.8,968

In [13]:
df[["Year","Month", "Day", "Hour", "Minute", "Solar Zenith Angle"]]

        Year  Month  Day  Hour  Minute  Solar Zenith Angle
0       2021      1    1     0       0              167.75
1       2021      1    1     0       5              168.34
2       2021      1    1     0      10              168.85
3       2021      1    1     0      15              169.26
4       2021      1    1     0      20              169.58
...      ...    ...  ...   ...     ...                 ...
105115  2021     12   31    23      35              163.99
105116  2021     12   31    23      40              164.83
105117  2021     12   31    23      45              165.63
105118  2021     12   31    23      50              166.39
105119  2021     12   31    23      55              167.10

[105120 rows x 6 columns]

In [20]:
df['ts'] = pd.to_datetime(df[['Year','Month','Day','Hour','Minute']])


mask = (df['ts'] >= '2021-07-07') & (df['ts'] < '2021-07-10')
sub = df.loc[mask].copy()
sub[["Year","Month", "Day", "Hour", "Minute", "Solar Zenith Angle"]]
sub['datetime'] = pd.to_datetime(sub[['Year','Month','Day','Hour','Minute']])
two_cols = pd.DataFrame({
    'datetime': sub['datetime'],
    'sun_direction': sub["Solar Zenith Angle"]
})
two_cols

                 datetime  sun_direction
53856 2021-07-07 00:00:00         123.82
53857 2021-07-07 00:05:00         123.98
53858 2021-07-07 00:10:00         124.11
53859 2021-07-07 00:15:00         124.21
53860 2021-07-07 00:20:00         124.29
...                   ...            ...
54715 2021-07-09 23:35:00         123.01
54716 2021-07-09 23:40:00         123.28
54717 2021-07-09 23:45:00         123.54
54718 2021-07-09 23:50:00         123.77
54719 2021-07-09 23:55:00         123.98

[864 rows x 2 columns]